export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const LOAD_CONVERSATION_LIST = 'LOAD_CONVERSATION_LIST';
export const UPDATE_CONVERSATION_LIST = 'UPDATE_CONVERSATION_LIST';
